### ISSUE TITLE
Mecanum Wheel doesn't spawn at RVIZ

### ISSUE THREAD

**Issue by Mettikodeva** [deborggraever/ros2-mecanum-bot#1]
the mecanum wheel doesn't spawn at RVIZ and can't find the joint state controller.
should I install the joint_state_controller pkg, but I can't find it on ROS2 or I should bridge it from ROS1?
and why " rl_wheel_joint position state interface not found" this is happen?

While run the [mecanum_bringup](https://github.com/deborggraever/ros2-mecanum-bot#build-and-run)
Could not configure controller with name 'joint_state_controller' because no controller with this name exists
**_wheel_joint position state interface not found
![image](https://user-images.githubusercontent.com/70711951/215435817-b65d864f-d70c-480c-829e-f29730aaadb7.png)

while executing the [#visualize-the-robot](https://github.com/deborggraever/ros2-mecanum-bot#visualize-the-robot)
Invalid frame ID "rr_wheel_link" passed to canTransform argument source_frame - frame does not exist
![image](https://user-images.githubusercontent.com/70711951/215437520-1ea609b0-0df0-4b5c-8a8c-1706a15d8b67.png)

 - OS: Ubuntu-20.04
 - ROS: Humble

**Comment by shovington** [comment]
Did you find a solution? I got the exact same problem.

- OS: Ubuntu 22.04
- ROS: Humble

**Comment by deborggraever** [comment]
Looked into the problem. The current humble branch is still work in progress.

U need the joint state publisher package.
`sudo apt install ros-humble-joint-state-publisher`

First terminal
`ros2 launch mecanumbot_bringup mecanumbot_state_publisher.py`

Second terminal
`ros2 launch mecanumbot_bringup rviz2.py`

No errors and wheels are visisble
