### ISSUE TITLE
Some wheels doesn't spawn at RVIZ

### ISSUE THREAD

**Issue by joaopaulomo** [deborggraever/ros2-mecanum-bot#4]
I run the command to open RViz, and some wheels simply don't appear
![dont](https://github.com/deborggraever/ros2-mecanum-bot/assets/92831575/5130091b-8e40-4ad7-bf1e-4db7177d6e4f)

**Comment by deborggraever** [comment]
Please check #1 and let me know if this fixes your issue

Kind regards,
Randy

**Comment by deborggraever** [comment]
Wheels are now visible using main branch (PR #7)
