### ISSUE TITLE
foxy branch tip header file not found

### ISSUE THREAD

**Issue by Vsonic12138** [deborggraever/ros2-mecanum-bot#5]
ubuntu2004@ubuntu2004-virtual-machine:~/Desktop/ros2Mecanum/ros2-mecanum-bot$ colcon build
Starting >>> mecanumbot_description
Starting >>> mecanumbot_control                      
Starting >>> mecanumbot_controller                                                           
Starting >>> mecanumbot_hardware                                                                 
Starting >>> mecanumbot_teleop                                                                   
Finished <<< mecanumbot_description [1.51s]                                                      
--- stderr: mecanumbot_control                                             
/home/ubuntu2004/Desktop/ros2Mecanum/ros2-mecanum-bot/src/ros2-mecanum-bot/mecanumbot_control/src/mecanumbot_control_node.cpp:4:10: fatal error: realtime_tools/thread_priority.hpp: 没有那个文件或目录
    4 | #include <realtime_tools/thread_priority.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/mecanumbot_control_node.dir/build.make:63：CMakeFiles/mecanumbot_control_node.dir/src/mecanumbot_control_node.cpp.o] 错误 1
make[1]: *** [CMakeFiles/Makefile2:78：CMakeFiles/mecanumbot_control_node.dir/all] 错误 2
make: *** [Makefile:141：all] 错误 2
---
Failed   <<< mecanumbot_control [1.51s, exited with code 2]
Aborted  <<< mecanumbot_teleop [1.03s]
Aborted  <<< mecanumbot_hardware [2.53s]                                                 
Aborted  <<< mecanumbot_controller [2.69s]

Summary: 1 package finished [5.27s]
  1 package failed: mecanumbot_control
  3 packages aborted: mecanumbot_controller mecanumbot_hardware mecanumbot_teleop
  3 packages had stderr output: mecanumbot_control mecanumbot_controller mecanumbot_hardware
  1 package not processed

Why this happend?
![屏幕截图 2024-02-02 182604](https://github.com/deborggraever/ros2-mecanum-bot/assets/100191057/e46f65d8-eb2e-4c63-b491-fa2223a01ceb)

i already install the ros-foxy-realtime-tools

**Comment by deborggraever** [comment]
Hi,

Please check #3 to see if this fix the issue on Foxy as well.

Kind regards,
Randy

**Comment by deborggraever** [comment]
As Foxy is EOL, this project will no longer support Foxy (see #11)
